name: living_atlas_kb_example
description: Example app for living_atlas_kb_client.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  living_atlas_kb_client:
    path: ../

flutter:
  uses-material-design: true
